spring:
  application:
    name: boardroom-api
  jackson:
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:mysql://localhost:3306/boardroom?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        prefix: boardroom
        physical-strategy: org.thraex.boardroom.base.PrefixPhysicalNamingStrategy

server:
  port: 8037
