spring:
  application:
    name: thraex-boardroom
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=GMT
    username: root
    password: hanzo

logging:
  level:
    org.thraex.test: debug
