server:
  port: 8037

spring:
  application:
    name: fund-admin
  security:
    user:
      name: master
      password: admin
      roles: SUPER_ADMIN
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/fund_admin?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.thraex.admin.generics.naming.PrefixPhysicalNamingStrategy
        prefix: base
